import React, { useState } from 'react';
import { CalculationResults, UserProfile, FitnessGoal } from '../types';
import { 
  Flame, 
  Activity, 
  TrendingDown, 
  TrendingUp, 
  Heart, 
  Droplets, 
  Dna, 
  ShieldCheck, 
  Check, 
  Copy, 
  Share2, 
  Target, 
  ArrowRight,
  Info,
  PieChart,
  Sparkles
} from 'lucide-react';

interface ResultsDashboardProps {
  results: CalculationResults;
  profile: UserProfile;
  onGoalChange: (goal: FitnessGoal) => void;
  onOpenCoach: () => void;
  onScrollToForm?: () => void;
}

const formatNumber = (val: number, maxDecimals: number = 1): string => {
  if (isNaN(val) || !isFinite(val)) return '0';
  const rounded = Math.round((val + Number.EPSILON) * Math.pow(10, maxDecimals)) / Math.pow(10, maxDecimals);
  return rounded % 1 === 0 ? rounded.toString() : rounded.toFixed(maxDecimals);
};

export const ResultsDashboard: React.FC<ResultsDashboardProps> = ({
  results,
  profile,
  onGoalChange,
  onOpenCoach,
  onScrollToForm,
}) => {
  const [macroTab, setMacroTab] = useState<'deficit' | 'maintenance' | 'surplus'>('maintenance');
  const [copied, setCopied] = useState(false);

  const activeMacros = results.macros[macroTab];

  const handleCopyReport = () => {
    const reportText = `=== BMR & TDEE CALORIE ASSESSMENT REPORT ===
👤 Biological Sex: ${profile.gender.toUpperCase()}
🎂 Age: ${profile.age} years | Height: ${profile.heightCm} cm | Weight: ${profile.weightKg} kg
⚡ BMR (Basal Metabolic Rate): ${formatNumber(results.bmr)} kcal/day
🔥 TDEE (Maintenance Calories): ${formatNumber(results.tdee)} kcal/day

🎯 CALORIE DEFICIT (FAT LOSS):
- Mild Cut (-250 kcal): ${formatNumber(results.deficitTiers.mild.calories)} kcal/day (-0.25 kg/wk)
- Standard Cut (-500 kcal): ${formatNumber(results.deficitTiers.moderate.calories)} kcal/day (-0.5 kg/wk)
- Aggressive Cut (-750 kcal): ${formatNumber(results.deficitTiers.aggressive.calories)} kcal/day (-0.75 kg/wk)

💪 CALORIE SURPLUS (MUSCLE GAIN):
- Lean Bulk (+250 kcal): ${formatNumber(results.surplusTiers.lean.calories)} kcal/day (+0.25 kg/wk)
- Standard Bulk (+500 kcal): ${formatNumber(results.surplusTiers.moderate.calories)} kcal/day (+0.5 kg/wk)
- Aggressive Bulk (+750 kcal): ${formatNumber(results.surplusTiers.aggressive.calories)} kcal/day (+0.75 kg/wk)

🥗 RECOMMENDED MACROS (MAINTENANCE):
- Protein: ${results.macros.maintenance.proteinGrams}g (${results.macros.maintenance.proteinCalories} kcal)
- Carbs: ${results.macros.maintenance.carbsGrams}g (${results.macros.maintenance.carbsCalories} kcal)
- Fats: ${results.macros.maintenance.fatsGrams}g (${results.macros.maintenance.fatsCalories} kcal)

💧 Daily Water Target: ${results.waterIntakeLiters} Liters
⚖️ BMI: ${results.bmi} (${results.bmiCategory})
Generated by BMR Calculator AI`;

    navigator.clipboard.writeText(reportText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  return (
    <div id="results-dashboard" className="space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-500">
      {/* Top Banner with Quick Actions */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 p-4 rounded-2xl bg-gradient-to-r from-cyan-950/60 via-slate-900/80 to-blue-950/60 border border-cyan-500/40 backdrop-blur-md">
        <div>
          <div className="text-xs font-mono text-cyan-400 uppercase tracking-wider flex items-center gap-1.5">
            <ShieldCheck className="w-4 h-4" /> METABOLIC CALCULATION VERIFIED
          </div>
          <h2 className="text-xl font-bold text-white font-display">
            Your Energy Expenditure & Calorie Roadmap
          </h2>
        </div>

        <div className="flex items-center gap-2 flex-wrap sm:flex-nowrap">
          {onScrollToForm && (
            <button
              type="button"
              id="modify-biometrics-btn"
              onClick={onScrollToForm}
              className="px-3 py-2 rounded-xl bg-slate-900 border border-slate-700 hover:border-cyan-400 text-xs font-mono text-cyan-300 hover:text-white transition-all flex items-center gap-1.5 shadow-sm"
              title="Return to form to adjust biometrics"
            >
              <span>↑ ADJUST BIOMETRICS</span>
            </button>
          )}

          <button
            type="button"
            id="copy-report-btn"
            onClick={handleCopyReport}
            className="px-3.5 py-2 rounded-xl bg-slate-900 border border-slate-700 hover:border-cyan-400 text-xs font-mono text-slate-200 hover:text-white transition-all flex items-center gap-1.5 shadow-sm"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5 text-cyan-400" />}
            <span>{copied ? 'COPIED!' : 'COPY SUMMARY'}</span>
          </button>

          <button
            type="button"
            id="open-coach-btn"
            onClick={onOpenCoach}
            className="px-4 py-2 rounded-xl bg-gradient-to-r from-cyan-500 to-blue-600 hover:from-cyan-400 hover:to-blue-500 text-slate-950 font-bold text-xs font-mono transition-all flex items-center gap-1.5 shadow-lg shadow-cyan-500/20"
          >
            <Sparkles className="w-3.5 h-3.5 fill-slate-950" />
            <span>AI COACH ADVICE</span>
          </button>
        </div>
      </div>

      {/* Hero Metric Cards: BMR & Maintenance TDEE */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {/* BMR Card */}
        <div className="p-6 rounded-2xl bg-gradient-to-br from-[#0b1b36] to-[#071124] border border-cyan-500/40 shadow-xl relative overflow-hidden group">
          <div className="absolute top-0 right-0 w-32 h-32 bg-cyan-500/10 rounded-full blur-3xl pointer-events-none group-hover:bg-cyan-500/20 transition-all" />
          
          <div className="flex items-center justify-between mb-3">
            <span className="text-xs font-mono text-cyan-400 uppercase tracking-wider flex items-center gap-1.5">
              <Heart className="w-4 h-4 text-cyan-400" /> BASAL METABOLIC RATE (BMR)
            </span>
            <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-cyan-950 border border-cyan-800 text-cyan-300">
              0% EXERCISE BASELINE
            </span>
          </div>

          <div className="flex items-baseline gap-2 mb-2">
            <span className="text-4xl lg:text-5xl font-black text-white font-mono tracking-tight">{formatNumber(results.bmr)}</span>
            <span className="text-sm font-mono text-cyan-400 uppercase font-semibold">Calories / Day</span>
          </div>

          <p className="text-xs text-slate-300 leading-relaxed">
            The fundamental energy burned by your vital organs (heart, brain, lungs, liver) while in absolute resting state over 24 hours. Never consume below this threshold without clinical supervision.
          </p>
        </div>

        {/* TDEE Maintenance Card */}
        <div className="p-6 rounded-2xl bg-gradient-to-br from-[#0c2438] to-[#071825] border border-emerald-500/40 shadow-xl relative overflow-hidden group glow-emerald">
          <div className="absolute top-0 right-0 w-32 h-32 bg-emerald-500/10 rounded-full blur-3xl pointer-events-none group-hover:bg-emerald-500/20 transition-all" />
          
          <div className="flex items-center justify-between mb-3">
            <span className="text-xs font-mono text-emerald-400 uppercase tracking-wider flex items-center gap-1.5">
              <Activity className="w-4 h-4 text-emerald-400" /> TOTAL DAILY ENERGY (TDEE)
            </span>
            <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-emerald-950 border border-emerald-800 text-emerald-300">
              MAINTENANCE TARGET
            </span>
          </div>

          <div className="flex items-baseline gap-2 mb-2">
            <span className="text-4xl lg:text-5xl font-black text-emerald-300 font-mono tracking-tight">{formatNumber(results.tdee)}</span>
            <span className="text-sm font-mono text-emerald-400 uppercase font-semibold">Calories / Day</span>
          </div>

          <p className="text-xs text-slate-300 leading-relaxed">
            Your exact daily maintenance intake incorporating BMR, digestion (TEF), Non-Exercise Activity (NEAT), and workouts. Eating this amount keeps your bodyweight static.
          </p>
        </div>
      </div>

      {/* Secondary Biometrics Strip (Ideal Weight, Water, Protein) */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
        {/* Ideal Weight */}
        <div className="p-3.5 rounded-xl bg-slate-950/70 border border-slate-800/80">
          <div className="text-[11px] font-mono text-slate-400 uppercase flex items-center gap-1 font-bold">
            <Target className="w-3.5 h-3.5 text-blue-400" /> Ideal Body Weight Range
          </div>
          <div className="text-lg font-bold font-mono text-white mt-1">
            {profile.weightUnit === 'kg' 
              ? `${results.idealWeightRangeKg.min} – ${results.idealWeightRangeKg.max} kg`
              : `${results.idealWeightRangeLbs.min} – ${results.idealWeightRangeLbs.max} lbs`}
          </div>
        </div>

        {/* Daily Water */}
        <div className="p-3.5 rounded-xl bg-slate-950/70 border border-slate-800/80">
          <div className="text-[11px] font-mono text-slate-400 uppercase flex items-center gap-1 font-bold">
            <Droplets className="w-3.5 h-3.5 text-cyan-400" /> Daily Water Intake
          </div>
          <div className="text-lg font-bold font-mono text-cyan-300 mt-1">
            {results.waterIntakeLiters} L <span className="text-xs text-slate-400 font-normal font-sans">({results.waterIntakeOz} oz)</span>
          </div>
        </div>

        {/* Protein Target */}
        <div className="p-3.5 rounded-xl bg-slate-950/70 border border-slate-800/80">
          <div className="text-[11px] font-mono text-slate-400 uppercase flex items-center gap-1 font-bold">
            <Flame className="w-3.5 h-3.5 text-amber-400" /> Daily Protein Target
          </div>
          <div className="text-lg font-bold font-mono text-amber-300 mt-1">
            {results.proteinRecommendationGrams.min} – {results.proteinRecommendationGrams.max} g
          </div>
        </div>
      </div>

      {/* CALORIE DEFICIT (CUTTING) SECTION */}
      <div className="p-6 rounded-2xl bg-[#09152a] border border-cyan-500/30 shadow-xl">
        <div className="flex items-center justify-between mb-4">
          <div className="flex items-center gap-2.5">
            <div className="w-8 h-8 rounded-lg bg-cyan-500/20 border border-cyan-500/40 flex items-center justify-center text-cyan-400">
              <TrendingDown className="w-4 h-4" />
            </div>
            <div>
              <h3 className="text-base font-bold text-white font-display">CALORIE DEFICIT ROADMAP (FAT LOSS)</h3>
              <p className="text-xs text-slate-400">How many calories to eat daily to burn subcutaneous & visceral body fat</p>
            </div>
          </div>
          <span className="text-xs font-mono text-cyan-400 bg-cyan-950/80 px-2.5 py-1 rounded-full border border-cyan-500/30">
            3 TIERS AVAILABLE
          </span>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-3.5">
          {/* Mild Deficit */}
          <div 
            onClick={() => onGoalChange('deficit_mild')}
            className={`p-4 rounded-xl border cursor-pointer transition-all ${
              profile.goal === 'deficit_mild'
                ? 'bg-cyan-500/20 border-cyan-400 glow-cyan-sm scale-[1.02]'
                : 'bg-slate-950/60 border-slate-800 hover:border-slate-700 hover:bg-slate-900/50'
            }`}
          >
            <div className="flex items-center justify-between text-xs font-mono text-cyan-300 font-bold mb-1">
              <span>{results.deficitTiers.mild.label}</span>
              <span className="text-[10px] bg-cyan-950 px-1.5 py-0.5 rounded text-cyan-400">-250 kcal</span>
            </div>
            <div className="text-2xl font-black font-mono text-white my-1.5">
              {formatNumber(results.deficitTiers.mild.calories)} <span className="text-xs font-normal text-slate-400">kcal/day</span>
            </div>
            <div className="text-xs font-bold text-emerald-400 font-mono mb-2">
              ~{results.deficitTiers.mild.weeklyLossKg} kg ({results.deficitTiers.mild.weeklyLossLbs} lbs) / week
            </div>
            <p className="text-[11px] text-slate-300 leading-snug">
              {results.deficitTiers.mild.description}
            </p>
          </div>

          {/* Standard Deficit */}
          <div 
            onClick={() => onGoalChange('deficit_moderate')}
            className={`p-4 rounded-xl border cursor-pointer transition-all relative ${
              profile.goal === 'deficit_moderate'
                ? 'bg-cyan-500/20 border-cyan-400 glow-cyan scale-[1.02]'
                : 'bg-slate-950/60 border-slate-800 hover:border-slate-700 hover:bg-slate-900/50'
            }`}
          >
            <div className="absolute -top-2.5 right-3 bg-gradient-to-r from-cyan-400 to-blue-500 text-black text-[9px] font-black uppercase font-mono px-2 py-0.5 rounded-full shadow-md">
              RECOMMENDED
            </div>
            <div className="flex items-center justify-between text-xs font-mono text-cyan-300 font-bold mb-1">
              <span>{results.deficitTiers.moderate.label}</span>
              <span className="text-[10px] bg-cyan-950 px-1.5 py-0.5 rounded text-cyan-400">-500 kcal</span>
            </div>
            <div className="text-2xl font-black font-mono text-white my-1.5">
              {formatNumber(results.deficitTiers.moderate.calories)} <span className="text-xs font-normal text-slate-400">kcal/day</span>
            </div>
            <div className="text-xs font-bold text-emerald-400 font-mono mb-2">
              ~{results.deficitTiers.moderate.weeklyLossKg} kg ({results.deficitTiers.moderate.weeklyLossLbs} lbs) / week
            </div>
            <p className="text-[11px] text-slate-300 leading-snug">
              {results.deficitTiers.moderate.description}
            </p>
          </div>

          {/* Aggressive Deficit */}
          <div 
            onClick={() => onGoalChange('deficit_aggressive')}
            className={`p-4 rounded-xl border cursor-pointer transition-all ${
              profile.goal === 'deficit_aggressive'
                ? 'bg-cyan-500/20 border-cyan-400 glow-cyan-sm scale-[1.02]'
                : 'bg-slate-950/60 border-slate-800 hover:border-slate-700 hover:bg-slate-900/50'
            }`}
          >
            <div className="flex items-center justify-between text-xs font-mono text-cyan-300 font-bold mb-1">
              <span>{results.deficitTiers.aggressive.label}</span>
              <span className="text-[10px] bg-cyan-950 px-1.5 py-0.5 rounded text-cyan-400">-750 kcal</span>
            </div>
            <div className="text-2xl font-black font-mono text-white my-1.5">
              {formatNumber(results.deficitTiers.aggressive.calories)} <span className="text-xs font-normal text-slate-400">kcal/day</span>
            </div>
            <div className="text-xs font-bold text-emerald-400 font-mono mb-2">
              ~{results.deficitTiers.aggressive.weeklyLossKg} kg ({results.deficitTiers.aggressive.weeklyLossLbs} lbs) / week
            </div>
            <p className="text-[11px] text-slate-300 leading-snug">
              {results.deficitTiers.aggressive.description}
            </p>
          </div>
        </div>
      </div>

      {/* CALORIE SURPLUS (BULKING) SECTION */}
      <div className="p-6 rounded-2xl bg-[#09152a] border border-amber-500/30 shadow-xl">
        <div className="flex items-center justify-between mb-4">
          <div className="flex items-center gap-2.5">
            <div className="w-8 h-8 rounded-lg bg-amber-500/20 border border-amber-500/40 flex items-center justify-center text-amber-400">
              <TrendingUp className="w-4 h-4" />
            </div>
            <div>
              <h3 className="text-base font-bold text-white font-display">CALORIE SURPLUS ROADMAP (MUSCLE GROWTH)</h3>
              <p className="text-xs text-slate-400">How much surplus energy to fuel muscular hypertrophy & heavy gym progression</p>
            </div>
          </div>
          <span className="text-xs font-mono text-amber-400 bg-amber-950/80 px-2.5 py-1 rounded-full border border-amber-500/30">
            3 TIERS AVAILABLE
          </span>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-3.5">
          {/* Lean Bulk */}
          <div 
            onClick={() => onGoalChange('surplus_lean')}
            className={`p-4 rounded-xl border cursor-pointer transition-all ${
              profile.goal === 'surplus_lean'
                ? 'bg-amber-500/20 border-amber-400 glow-amber scale-[1.02]'
                : 'bg-slate-950/60 border-slate-800 hover:border-slate-700 hover:bg-slate-900/50'
            }`}
          >
            <div className="flex items-center justify-between text-xs font-mono text-amber-300 font-bold mb-1">
              <span>{results.surplusTiers.lean.label}</span>
              <span className="text-[10px] bg-amber-950 px-1.5 py-0.5 rounded text-amber-400">+250 kcal</span>
            </div>
            <div className="text-2xl font-black font-mono text-white my-1.5">
              {formatNumber(results.surplusTiers.lean.calories)} <span className="text-xs font-normal text-slate-400">kcal/day</span>
            </div>
            <div className="text-xs font-bold text-amber-400 font-mono mb-2">
              ~{results.surplusTiers.lean.weeklyGainKg} kg ({results.surplusTiers.lean.weeklyGainLbs} lbs) / week
            </div>
            <p className="text-[11px] text-slate-300 leading-snug">
              {results.surplusTiers.lean.description}
            </p>
          </div>

          {/* Standard Bulk */}
          <div 
            onClick={() => onGoalChange('surplus_moderate')}
            className={`p-4 rounded-xl border cursor-pointer transition-all ${
              profile.goal === 'surplus_moderate'
                ? 'bg-amber-500/20 border-amber-400 glow-amber scale-[1.02]'
                : 'bg-slate-950/60 border-slate-800 hover:border-slate-700 hover:bg-slate-900/50'
            }`}
          >
            <div className="flex items-center justify-between text-xs font-mono text-amber-300 font-bold mb-1">
              <span>{results.surplusTiers.moderate.label}</span>
              <span className="text-[10px] bg-amber-950 px-1.5 py-0.5 rounded text-amber-400">+500 kcal</span>
            </div>
            <div className="text-2xl font-black font-mono text-white my-1.5">
              {formatNumber(results.surplusTiers.moderate.calories)} <span className="text-xs font-normal text-slate-400">kcal/day</span>
            </div>
            <div className="text-xs font-bold text-amber-400 font-mono mb-2">
              ~{results.surplusTiers.moderate.weeklyGainKg} kg ({results.surplusTiers.moderate.weeklyGainLbs} lbs) / week
            </div>
            <p className="text-[11px] text-slate-300 leading-snug">
              {results.surplusTiers.moderate.description}
            </p>
          </div>

          {/* Aggressive Bulk */}
          <div 
            onClick={() => onGoalChange('surplus_aggressive')}
            className={`p-4 rounded-xl border cursor-pointer transition-all ${
              profile.goal === 'surplus_aggressive'
                ? 'bg-amber-500/20 border-amber-400 glow-amber scale-[1.02]'
                : 'bg-slate-950/60 border-slate-800 hover:border-slate-700 hover:bg-slate-900/50'
            }`}
          >
            <div className="flex items-center justify-between text-xs font-mono text-amber-300 font-bold mb-1">
              <span>{results.surplusTiers.aggressive.label}</span>
              <span className="text-[10px] bg-amber-950 px-1.5 py-0.5 rounded text-amber-400">+750 kcal</span>
            </div>
            <div className="text-2xl font-black font-mono text-white my-1.5">
              {formatNumber(results.surplusTiers.aggressive.calories)} <span className="text-xs font-normal text-slate-400">kcal/day</span>
            </div>
            <div className="text-xs font-bold text-amber-400 font-mono mb-2">
              ~{results.surplusTiers.aggressive.weeklyGainKg} kg ({results.surplusTiers.aggressive.weeklyGainLbs} lbs) / week
            </div>
            <p className="text-[11px] text-slate-300 leading-snug">
              {results.surplusTiers.aggressive.description}
            </p>
          </div>
        </div>
      </div>

      {/* MACRONUTRIENT RATIO BLUEPRINT */}
      <div className="p-6 rounded-2xl bg-[#081224] border border-cyan-500/30 shadow-xl">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 mb-6">
          <div className="flex items-center gap-2.5">
            <div className="w-8 h-8 rounded-lg bg-cyan-500/20 border border-cyan-500/40 flex items-center justify-center text-cyan-400">
              <PieChart className="w-4 h-4" />
            </div>
            <div>
              <h3 className="text-base font-bold text-white font-display">MACRONUTRIENT DISTRIBUTION BLUEPRINT</h3>
              <p className="text-xs text-slate-400">Exact grams and caloric percentages for Protein, Carbs, and Fats</p>
            </div>
          </div>

          {/* Macro Split Selector Tabs */}
          <div className="flex items-center bg-slate-950 p-1 rounded-xl border border-slate-800">
            <button
              type="button"
              onClick={() => setMacroTab('deficit')}
              className={`px-3 py-1.5 rounded-lg text-xs font-mono font-bold transition-all ${
                macroTab === 'deficit' ? 'bg-cyan-500 text-black shadow-md' : 'text-slate-400 hover:text-white'
              }`}
            >
              Cutting Macros
            </button>
            <button
              type="button"
              onClick={() => setMacroTab('maintenance')}
              className={`px-3 py-1.5 rounded-lg text-xs font-mono font-bold transition-all ${
                macroTab === 'maintenance' ? 'bg-emerald-500 text-black shadow-md' : 'text-slate-400 hover:text-white'
              }`}
            >
              Maintain Macros
            </button>
            <button
              type="button"
              onClick={() => setMacroTab('surplus')}
              className={`px-3 py-1.5 rounded-lg text-xs font-mono font-bold transition-all ${
                macroTab === 'surplus' ? 'bg-amber-500 text-black shadow-md' : 'text-slate-400 hover:text-white'
              }`}
            >
              Bulking Macros
            </button>
          </div>
        </div>

        {/* Macro Visual Progress Bars */}
        <div className="w-full h-3 rounded-full bg-slate-900 overflow-hidden flex mb-6 border border-slate-800">
          <div 
            style={{ width: `${activeMacros.proteinPercent}%` }} 
            className="h-full bg-cyan-400 transition-all duration-500" 
            title={`Protein ${activeMacros.proteinPercent}%`}
          />
          <div 
            style={{ width: `${activeMacros.carbsPercent}%` }} 
            className="h-full bg-blue-500 transition-all duration-500" 
            title={`Carbs ${activeMacros.carbsPercent}%`}
          />
          <div 
            style={{ width: `${activeMacros.fatsPercent}%` }} 
            className="h-full bg-amber-400 transition-all duration-500" 
            title={`Fats ${activeMacros.fatsPercent}%`}
          />
        </div>

        {/* 3 Columns: Protein, Carbs, Fats */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          {/* Protein */}
          <div className="p-4 rounded-xl bg-slate-950/80 border border-cyan-500/40">
            <div className="flex items-center justify-between mb-2">
              <span className="text-xs font-mono text-cyan-400 uppercase font-bold flex items-center gap-1.5">
                <span className="w-2.5 h-2.5 rounded-full bg-cyan-400" />
                PROTEIN (4 kcal/g)
              </span>
              <span className="text-xs font-mono text-slate-300 font-bold">{activeMacros.proteinPercent}%</span>
            </div>
            <div className="text-3xl font-black font-mono text-white mb-1">
              {activeMacros.proteinGrams} <span className="text-sm font-normal text-cyan-400">grams</span>
            </div>
            <div className="text-xs text-slate-400 font-mono">
              {activeMacros.proteinCalories} Calories total
            </div>
            <div className="text-[11px] text-slate-400 mt-2 border-t border-slate-800/80 pt-2">
              Vital for muscle protein synthesis (MPS) & recovery.
            </div>
          </div>

          {/* Carbohydrates */}
          <div className="p-4 rounded-xl bg-slate-950/80 border border-blue-500/40">
            <div className="flex items-center justify-between mb-2">
              <span className="text-xs font-mono text-blue-400 uppercase font-bold flex items-center gap-1.5">
                <span className="w-2.5 h-2.5 rounded-full bg-blue-500" />
                CARBOHYDRATES (4 kcal/g)
              </span>
              <span className="text-xs font-mono text-slate-300 font-bold">{activeMacros.carbsPercent}%</span>
            </div>
            <div className="text-3xl font-black font-mono text-white mb-1">
              {activeMacros.carbsGrams} <span className="text-sm font-normal text-blue-400">grams</span>
            </div>
            <div className="text-xs text-slate-400 font-mono">
              {activeMacros.carbsCalories} Calories total
            </div>
            <div className="text-[11px] text-slate-400 mt-2 border-t border-slate-800/80 pt-2">
              Primary fuel for high-intensity lifting & muscle glycogen.
            </div>
          </div>

          {/* Healthy Fats */}
          <div className="p-4 rounded-xl bg-slate-950/80 border border-amber-500/40">
            <div className="flex items-center justify-between mb-2">
              <span className="text-xs font-mono text-amber-400 uppercase font-bold flex items-center gap-1.5">
                <span className="w-2.5 h-2.5 rounded-full bg-amber-400" />
                HEALTHY FATS (9 kcal/g)
              </span>
              <span className="text-xs font-mono text-slate-300 font-bold">{activeMacros.fatsPercent}%</span>
            </div>
            <div className="text-3xl font-black font-mono text-white mb-1">
              {activeMacros.fatsGrams} <span className="text-sm font-normal text-amber-400">grams</span>
            </div>
            <div className="text-xs text-slate-400 font-mono">
              {activeMacros.fatsCalories} Calories total
            </div>
            <div className="text-[11px] text-slate-400 mt-2 border-t border-slate-800/80 pt-2">
              Essential for hormonal balance, testosterone & joints.
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
